version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: statement_user
      POSTGRES_PASSWORD: statement_password
      POSTGRES_DB: statement_sense
      POSTGRES_INITDB_ARGS: '--data-checksums --no-locale'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U statement_user -d statement_sense"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 10s
    networks:
      - app-network

  # Ollama LLM Service
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - app-network

  # FastAPI Backend (Development)
  backend:
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=statement_user
      - DB_PASS=statement_password
      - DB_NAME=statement_sense
      - OLLAMA_URL=http://ollama:11434
      - PROJECT_NAME=StatementSense (Dev)
      - LOG_LEVEL=DEBUG
    depends_on:
      postgres:
        condition: service_healthy
      ollama:
        condition: service_started
    networks:
      - app-network

  # React Frontend (Development)
  frontend:
    build:
      context: ./frontend
      target: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://backend:8000
      - VITE_APP_TITLE=StatementSense (Dev)
      - CHOKIDAR_USEPOLLING=true  # For hot reloading in Docker
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  ollama_data:
