"""Initial database schema

Revision ID: 6240c948d540
Revises: 
Create Date: 2025-06-11 22:24:56.475116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6240c948d540'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('upload_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('card_number_last4', sa.String(length=4), nullable=True),
    sa.Column('statement_period_start', sa.DateTime(), nullable=True),
    sa.Column('statement_period_end', sa.DateTime(), nullable=True),
    sa.Column('cut_date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.String(), nullable=True),
    sa.Column('pay_no_interest', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('minimum_payment', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('previous_balance', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_charges', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_payments', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('credit_limit', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('available_credit', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_balance', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('extraction_method', sa.Enum('MEXICAN_TEMPLATE', 'LLM_FALLBACK', 'HYBRID', name='extractionmethodenum'), nullable=True),
    sa.Column('overall_confidence', sa.Float(), nullable=True),
    sa.Column('processing_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'PARTIAL', name='processingstatusenum'), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_statements_id'), 'bank_statements', ['id'], unique=False)
    op.create_table('category_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('pattern', sa.String(), nullable=True),
    sa.Column('category', sa.Enum('ALIMENTACION', 'GASOLINERAS', 'SALUD', 'TRANSPORTE', 'ENTRETENIMIENTO', 'ROPA', 'SERVICIOS', 'EDUCACION', 'SEGUROS', 'TRANSFERENCIAS', 'INTERESES_COMISIONES', 'OTROS', name='transactioncategoryenum'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pattern')
    )
    op.create_index(op.f('ix_category_rules_id'), 'category_rules', ['id'], unique=False)
    op.create_index(op.f('ix_category_rules_keyword'), 'category_rules', ['keyword'], unique=True)
    op.create_table('processing_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statement_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('level', sa.Enum('INFO', 'WARNING', 'ERROR', 'DEBUG', name='loglevelenum'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['statement_id'], ['bank_statements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_logs_id'), 'processing_logs', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statement_id', sa.Integer(), nullable=False),
    sa.Column('operation_date', sa.DateTime(), nullable=False),
    sa.Column('charge_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('transaction_type', sa.Enum('CARGO', 'ABONO', name='transactiontypeenum'), nullable=False),
    sa.Column('category', sa.Enum('ALIMENTACION', 'GASOLINERAS', 'SALUD', 'TRANSPORTE', 'ENTRETENIMIENTO', 'ROPA', 'SERVICIOS', 'EDUCACION', 'SEGUROS', 'TRANSFERENCIAS', 'INTERESES_COMISIONES', 'OTROS', name='transactioncategoryenum'), nullable=True),
    sa.Column('original_category', sa.Enum('ALIMENTACION', 'GASOLINERAS', 'SALUD', 'TRANSPORTE', 'ENTRETENIMIENTO', 'ROPA', 'SERVICIOS', 'EDUCACION', 'SEGUROS', 'TRANSFERENCIAS', 'INTERESES_COMISIONES', 'OTROS', name='transactioncategoryenum'), nullable=True),
    sa.Column('categorization_confidence', sa.Float(), nullable=True),
    sa.Column('is_manual_edit', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['statement_id'], ['bank_statements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_processing_logs_id'), table_name='processing_logs')
    op.drop_table('processing_logs')
    op.drop_index(op.f('ix_category_rules_keyword'), table_name='category_rules')
    op.drop_index(op.f('ix_category_rules_id'), table_name='category_rules')
    op.drop_table('category_rules')
    op.drop_index(op.f('ix_bank_statements_id'), table_name='bank_statements')
    op.drop_table('bank_statements')
    # ### end Alembic commands ###
