"""add_file_size_to_bank_statements

Revision ID: eff706ded328
Revises: 6240c948d540
Create Date: 2025-06-11 22:40:56.736060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eff706ded328'
down_revision = '6240c948d540'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_statements', sa.Column('file_size', sa.Integer(), nullable=True, comment='File size in bytes'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank_statements', 'file_size')
    # ### end Alembic commands ###
